#!/usr/bin/env python
# StepSpace Init module for Step
# Autogenerated by WMCore.WMSpec.Steps.Builder

__all__ = []

from WMCore.WMRuntime.Bootstrap import establishStepSpace

def _Locator():
    pass

args = {}
args["TaskName"] = "GenSimFull"
args["StepName"] = "cmsRun1"
args["Locator"] = _Locator
stepSpace = establishStepSpace(**args)
