
#!/usr/bin/env python

#
# WMTaskSpace entry point
# Autogenerated by WMCore.WMSpec.Steps.BuildMaster Module
__all__ = []

from WMCore.WMRuntime.Bootstrap import establishTaskSpace
def _Locator():
    pass
args = {}

args["TaskName"] = "/pdmvserv_RVCMSSW_16_0_0_pre2QCD__STD_GPU_Pix_202_PU_KIT_251125_103426_8717/GenSimFull"
args["Locator"] = _Locator
taskSpace = establishTaskSpace(**args)
